# Generated by Django 3.2.18 on 2023-04-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_auto_20230320_0819"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="appinstallation",
            name="uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
