# Generated by Django 3.2.18 on 2023-04-03 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0023_auto_20230403_1843"),
        ("thumbnail", "0002_alter_thumbnail_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="thumbnail",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="app.app",
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="app_installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thumbnails",
                to="app.appinstallation",
            ),
        ),
    ]
